package com.mystudy.ex01_exception;

public class ExceptionFinally {
	 
	public static void main(String[] args) {
		// try ~ catch ~ finally
		System.out.println("---- main() 시작 -----");
		int num = 20;
		int result = 0;
		try {
			num = 0;
			result = 100 / num;
		}
		
		
		
		
		System.out.println("----- main() 종료 -----");
		
	}
	

}
